export const {
  PORT,
  FRONTEND_DEVELOPMENT_URL,
  FRONTEND_PRODUCTION_URL,
  NODE_ENV,
  MONGODB_URI,
  JWT_SECRET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_MAIN_FOLDER,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
} = process.env;
